import { createContext, useContext, useState, useEffect, useRef, useCallback } from "react";
import supabase from "../supabase";
import { useTenant } from "./TenantContext";
import { createRequestGuard } from "../utils/requestGuard";
const StoreInfoContext = createContext();
export function StoreInfoProvider({ children }) {
  const { slug, tenantId, isPublic, isTracking } = useTenant(); const [storeInfo, setStoreInfo] = useState({}); const guard = useRef(createRequestGuard()).current;
  const refreshStoreInfo = useCallback(async () => { if (isTracking || (isPublic && !slug)) return; const query = isPublic ? supabase.rpc("get_public_store", { p_slug: slug }) : supabase.from("store").select("*").eq("tenant_id", tenantId).maybeSingle(); const { data, error } = await query; if (!error) { const next = isPublic ? data?.[0] || {} : data || {}; setStoreInfo(next); return next; } return null; }, [isTracking, isPublic, slug, tenantId]);
  useEffect(() => { void refreshStoreInfo(); }, [refreshStoreInfo]);
  const updateStoreInfo = (details) => guard("store:update", async () => { if (isPublic || !tenantId) return { error: new Error("غير مصرح: لا توجد جلسة مدير مرتبطة بنشاط") }; const safeSlug = String(details.store_slug || "").trim().toLowerCase(); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(safeSlug)) return { error: new Error("الـ slug يجب أن يحتوي على أحرف إنجليزية وأرقام وشرطة فقط") }; const { data: store, error: storeError } = await supabase.from("store").update({ store_name: details.store_name, store_slug: safeSlug, phone: details.phone, email: details.email, tax_number: details.tax_number, currency: details.currency, address: details.address, receipt_footer: details.receipt_footer, logo_url: details.logo_url }).eq("tenant_id", tenantId).select("id").maybeSingle(); if (storeError) return { error: storeError }; if (!store) return { error: new Error("لم يتم العثور على ملف المتجر لهذا النشاط") }; const { error: tenantError } = await supabase.from("tenants").update({ name: details.store_name, slug: safeSlug, logo_url: details.logo_url, theme_config: details.theme_config || {} }).eq("id", tenantId).select("id").maybeSingle(); if (tenantError) return { error: tenantError }; setStoreInfo((prev) => ({ ...prev, ...details, store_slug: safeSlug })); return { error: null }; });
  return <StoreInfoContext.Provider value={{ storeInfo, updateStoreInfo, refreshStoreInfo }}>{children}</StoreInfoContext.Provider>;
}
export const useStore = () => { const context = useContext(StoreInfoContext); if (!context) throw new Error("useStore must be used within StoreInfoProvider"); return context; };
